use warnings;
use strict;
use Test::More;
use FindBin '$Bin';
use Image::PNG::Libpng ':all';
use Image::PNG::Const ':all';
use lib "$Bin/../t/";
use IPNGLT;
my $png = create_read_struct ();
$png->set_keep_unknown_chunks (PNG_HANDLE_CHUNK_ALWAYS);
open my $file, "<:raw", "$Bin/logo_icon128.v101.png";
$png->init_io ($file);
$png->read_png ();
my $wpng = copy_png ($png);
my $name = 'dUCk';
my $data = 'ABCDEFG';
$wpng->set_unknown_chunks ([{name => $name, data => $data, location => PNG_HAVE_IHDR}]);
my $ofile = "$Bin/chunks.png";
rmfile ($ofile);
$wpng->write_png_file ($ofile);
my $rpng = create_reader ($ofile);
$rpng->set_keep_unknown_chunks (PNG_HANDLE_CHUNK_ALWAYS);
$rpng->read_png ();
my $chunks = $rpng->get_unknown_chunks ();
cmp_ok (scalar (@$chunks), '==', 1, "got one unknown chunk");
is ($chunks->[0]{name}, $name, "retrieved name");
is ($chunks->[0]{data}, $data, "retrieved data");
done_testing ();
